language: php
dist: trusty

php:
  - 7.4
  - 7.3
  - 7.2

matrix:
  fast_finish: true

services:
  - mysql
  - postgresql
  - redis-server
  - memcached

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction
  - if [[ $TRAVIS_PHP_VERSION == 7.2 ]]; then
        printf "autodetect\n" | pecl install mcrypt-snapshot;
    fi

before_script:
  - ./tests/travis/mysql-setup.sh
  - ./tests/travis/postgresql-setup.sh
  - phpenv config-rm xdebug.ini || echo

script:
  - vendor/bin/phpstan analyse --memory-limit=-1 -c phpstan.neon
  - vendor/bin/phpstan analyse --memory-limit=-1 -c phpstan-tests.neon
  - cd tests && ../vendor/bin/phpunit --verbose --colors --exclude-group mssql,oci framework
