language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

services:
  - redis-server
  - memcached

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

before_script:
  - ./tests/travis/mysql-setup.sh
  - ./tests/travis/postgresql-setup.sh
  - ./tests/travis/memcache-setup.sh

script: cd tests && ../vendor/bin/phpunit --verbose --colors --no-globals-backup --exclude-group mssql,oci framework
