language: php

php:
  - 7.3
  - 7.2
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3

services:
  - redis-server
  - memcached

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction
  - if [[ $TRAVIS_PHP_VERSION == 7.2 ]]; then
        printf "autodetect\n" | pecl install mcrypt-snapshot;
    fi

before_script:
  # Disable DEPRECATE messages during PHPUnit initialization on PHP 7.2. To fix them, PHPUnit should be updated to 6.*
  - if [[ $TRAVIS_PHP_VERSION == 7.2 ]] || [[ $TRAVIS_PHP_VERSION == 7.3 ]]; then
      echo 'Disabled DEPRECATED notifications for PHP 7.2';
      echo 'error_reporting = E_ALL & ~E_DEPRECATED' >> /tmp/php-config.ini;
      phpenv config-add /tmp/php-config.ini;
    fi
  - ./tests/travis/mysql-setup.sh
  - ./tests/travis/postgresql-setup.sh
  - ./tests/travis/memcache-setup.sh

script: cd tests && ../vendor/bin/phpunit --verbose --colors --no-globals-backup --exclude-group mssql,oci framework
